### ISSUE TITLE
rexray fail to attach cinder volume

### ISSUE THREAD

**Issue by int32bit** [codedellemc/rexray#1047]
# Summary

Rexray fails to attach cinder volume

# Bug Reports

My OpenStack installed using DevStack, and the cinder backend is LVM. I succeed to attach to local manually.

I installed rexray refer to https://github.com/codedellemc/rexray, and succeed to create & delete cinder volume, but always fail to attach & mount.

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Wed, 13 Sep 2017 05:18:02 CST
```

## Expected Behavior

Run `rexray volume mount  test-volume` should attach volume to local and mount to specified dir.

## Actual Behavior

Fail to mount volume, the output as follows:

```
root@devstack:~# rexray volume mount int32bit-test-rexray
ID  Name  Status  Size  Path
FATA[0004] error mounting volume                         error.inner.instanceId=7590d98b-53cf-439c-824f-e79eebab4b36 error.inner.provider=cinder error.inner.volumeId=853ad8de-cb0f-49fb-ac72-977ca08bfca5 error.status=500 error.msg=error attaching volume volume=int32bit-test-rexray
```

And the log:

```
DEBU[0134] getting task service                          host=unix:///var/run/rexray/499313858.sock instanceID=cinder=7590d98b-53cf-439c-824f-e79eebab4b36 route=volumeAttach server=caramel-leg-wf service=cinder storageDriver=cinder time=1506751912592 tls=false txCR=150675
1912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
ERRO[0134] error attaching volume                        host=unix:///var/run/rexray/499313858.sock inner=Resource not found instanceID=cinder=7590d98b-53cf-439c-824f-e79eebab4b36 instanceId=7590d98b-53cf-439c-824f-e79eebab4b36 provider=cinder route=volumeAttach server=ca
ramel-leg-wf service=cinder storageDriver=cinder task=0 time=1506751912869 tls=false txCR=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1 volumeId=853ad8de-cb0f-49fb-ac72-977ca08bfca5
DEBU[0134] task completed                                host=unix:///var/run/rexray/499313858.sock instanceID=cinder=7590d98b-53cf-439c-824f-e79eebab4b36 route=volumeAttach server=caramel-leg-wf service=cinder storageDriver=cinder task=0 time=1506751912869 tls=false txCR
=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
ERRO[0134] error: api call failed                        error.instanceId=7590d98b-53cf-439c-824f-e79eebab4b36 error.provider=cinder error.volumeId=853ad8de-cb0f-49fb-ac72-977ca08bfca5 host=unix:///var/run/rexray/499313858.sock route=volumeAttach server=caramel-leg-wf tim
e=1506751912869 tls=false txCR=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
DEBU[0134] api call error json                           apiErr={"message":"error attaching volume","status":500,"error":{"inner":"Resource not found","instanceId":"7590d98b-53cf-439c-824f-e79eebab4b36","provider":"cinder","volumeId":"853ad8de-cb0f-49fb-ac72-977ca08bfca5"
}} host=unix:///var/run/rexray/499313858.sock route=volumeAttach server=caramel-leg-wf time=1506751912869 tls=false txCR=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
DEBU[0134] removing task                                 host=unix:///var/run/rexray/499313858.sock instanceID=cinder=7590d98b-53cf-439c-824f-e79eebab4b36 removedAfter=0s route=volumeAttach server=caramel-leg-wf service=cinder storageDriver=cinder task=0 tasksLen=1 time=1
506751912874 tls=false txCR=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
DEBU[0134] removed task                                  host=unix:///var/run/rexray/499313858.sock instanceID=cinder=7590d98b-53cf-439c-824f-e79eebab4b36 route=volumeAttach server=caramel-leg-wf service=cinder storageDriver=cinder task=0 tasksLen=0 time=1506751912877 tls
=false txCR=1506751912 txID=67e4674c-17c0-4739-459c-f9650d54d4c1
```

Or I mount in Docker:

```
root@devstack:~# docker run -t -i --rm --volume-driver rexray -v test-volume:/test-volume busybox
docker: Error response from daemon: error while mounting volume '/': VolumeDriver.Mount: {"Error":"error attaching volume"}.
ERRO[0002] error waiting for container: context canceled
```

## Steps To Reproduce

My OpenStack installed using DevStack(Master branch), my config as follows:

```yaml
root@devstack:~# cat /etc/rexray/config.yml
rexray:
  logLevel: warn
libstorage:
  logging:
    level: warn
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 1
        mount:
          preempt: true
cinder:
  authUrl:              http://10.0.2.15/identity/v3
  username:             admin
  password:             nomoresecret
  tenantId:             ae21d957967d4df0865411f0389ed7e8
  tenantName:           admin
  identityApiVersion:   3
  domainName:           Default
```
