### ISSUE TITLE
Cannot mount s3fs volume

### ISSUE THREAD

**Issue by n1b0r** [codedellemc/rexray#1048]
# Summary

Trying to setup rexay using s3fs provider with a minio endpoint.

I can create a volume but cannot mount it.

## Version

```shell
$ sudo rexray version --logLevel warn
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 21:18:02 UTC
```

## Expected Behavior

The volume should be mounted on host.

## Actual Behavior

Fail mounting the volume.

## Steps To Reproduce

1. Create a volume

```shell
$ sudo rexray volume create testvol --logLevel warn
ID       Name     Status     Size
testvol  testvol  available  0
```

2. mount it

```shell
$ sudo rexray volume mount testvol --logLevel warn
ID  Name  Status  Size  Path
FATA[0002] error mounting volume                         error=open testvol: no such file or directory volume=testvol
```

## Configuration Files

$ cat /etc/rexray/config.yml

```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
  service: s3fs
s3fs:
  accessKey: ****
  secretKey: ****
  endpoint: http://172.16.33.115:9000
  options:
  - url=http://172.16.33.115:9000
```

### Client Log

[gist](https://gist.github.com/n1b0r/0f74f3846d8d36febb19683fce0591f8)

**Comment by dahendel** [comment]
@n1b0r can you try and add these options in the config.yml:
```
  - use_path_request_style
  - allow_other
  - nonempty
```

**Comment by n1b0r** [comment]
@dahendel same result using the following configuration :

```
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
  service: s3fs
s3fs:
  accessKey: *****
  secretKey: *****
  endpoint: http://172.16.33.115:9000
  options:
  - url=http://172.16.33.115:9000
  - use_path_request_style
  - allow_other
  - nonempty
```

I can list, create, remove the volume but cannot mount it.

**Comment by dahendel** [comment]
@n1b0r  try setting the mount option in the s3fs under libstorage.
Here is what I used to test:
```

**Comment by n1b0r** [comment]
Still no luck could you paste your whole config please ?

**Comment by n1b0r** [comment]
Can you attach a volume ?

```
$ rexray volume attach testtoto --logLevel warn
FATA[0001] no volumes found                             
```

**Comment by n1b0r** [comment]
After mount command, I can see that a folder has been created under `/var/lib/rexray/`

```
$ rexray volume mount testtoto --logLevel warn
ID  Name  Status  Size  Path
FATA[0001] error mounting volume                         error=open testtoto: no such file or directory volume=testtoto
$ ls -al /var/lib/rexray/volumes/testtoto/
total 8
drwxr-xr-x 2 root root 4096 oct.   2 20:37 .
drwxr-xr-x 5 root root 4096 oct.   2 20:37 ..
```

**Comment by dahendel** [comment]
Here is my whole config
```
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        create:
          default:
            size: 100
        mount:
          rootPath: /rexray 
s3fs:
  accessKey: ***
  secretKey: ****
  endpoint: http://***
  options:
  - url=http://***
  - use_path_request_style
  - allow_other
  - nonempty
```

**Comment by dahendel** [comment]
Try changing root path to "/". That way it mounts the root of the volume instead of a folder rexray that isn't there. Error in my config. Sorry about that.

```
[root@host ~]# cat /etc/rexray/config.yml 
#rexray:
#  logLevel: debug
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        create:
          default:
            size: 100
        mount:
          rootPath: / 
s3fs:
  accessKey: ****
  secretKey: ****
  endpoint: http://****
  options:
  - url=http://****
  - use_path_request_style
  - allow_other
  - nonempty

[root@host ~]# rexray volume mount testing
ID       Name     Status    Size  Path
testing  testing  attached  0     /var/lib/libstorage/volumes/testing

[root@host ~]# ls /var/lib/libstorage/volumes/testing
testing.txt
```

**Comment by n1b0r** [comment]
Still the same error.

```
rexray:
  logLevel: debug
libstorage:
  service: s3fs
  integration:
    volume:
      operations:
        create:
          default:
            size: 100
        mount:
          rootPath: /
s3fs:
  accessKey: *****
  secretKey: ***
  endpoint: http://***:9000
  options:
  - url=http://****:9000
  - use_path_request_style
  - allow_other
  - nonempty
```

Why is your default storage into `/var/lib/libstorage` ? What OS are you using ?

**Comment by dahendel** [comment]
I am on CentOs7. Have you installed s3fs on your host?

**Comment by n1b0r** [comment]
Thanks for your comments. I did not installed s3fs.....

It seems to be working now. Thanks !!

**Comment by n1b0r** [comment]
I can now mount the volume using rexray command but cannot mount it using docker volume.

```
$ sudo rexray volume mount testrobin2 --logLevel warn
ID          Name        Status    Size  Path
testrobin2  testrobin2  attached  0     /var/lib/rexray/volumes/testrobin2/data
$ sudo docker run --rm -it --volume-driver rexray -v testrobin2:/tmp ubuntu
docker: Error response from daemon: chown /var/lib/rexray/volumes/testrobin2/data: no such file or directory.
See 'docker run --help'.
```

Did you already get this error ?

**Comment by dahendel** [comment]
I did not. I tested on docker 1.12 and a fresh docker host of the latest ce release. Try not creating the volume ahead of time with rexray. Just `docker run --rm -it --volume-driver rexray -v testrobin3:/tmp ubuntu`

**Comment by clintkitson** [comment]
Hello @n1b0r,

This error is likely being caused by your Docker daemon being run from inside of a container. It is having a problem accessing the `/var/lib/rexray/volumes` path, and in the past has been due to this.

Check your docker daemon process.

**Comment by n1b0r** [comment]
@clintkitson  the docker daemon is running on a Ubuntu 16.04 desktop.

@dahendel creating/mounting the volume using docker command produce

```
$ sudo docker run --rm -it --volume-driver rexray -v test15:/tmp ubuntu
docker: Error response from daemon: chown /var/lib/rexray/volumes/test15: input/output error.
```

**Comment by clintkitson** [comment]
@n1b0r Ok looks like a new error. Can you run the rexray commands manually for mounting, and then verify the same problems? `rexray volume mount`

If you are getting an i/o error it is likely related to S3FS itself and its interaction with the bucket that you specified.

**Comment by n1b0r** [comment]
@clintkitson Here is my tests

Mounting a volume using s3fs command

```
$ sudo mkdir /mnt/mybucket
$ sudo s3fs -f -d -o use_path_request_style -o url=http://localhost:9000 -o allow_other test12 /mnt/mybucket
$ ls /mnt/mybucket/
toto
$ touch /mnt/mybucket/tata
$ ls /mnt/mybucket/
tata  toto
```

Mounting the volume using rexray command

```
$ sudo rexray volume mount test12 --logLevel warn
ID      Name    Status    Size  Path
test12  test12  attached  0     /var/lib/rexray/volumes/test12
$ sudo rexray volume mount test12 --logLevel warn
ID      Name    Status    Size  Path
test12  test12  attached  0     /var/lib/rexray/volumes/test12
$ sudo ls /var/lib/rexray/volumes/test12/
tata  toto
$ sudo touch /var/lib/rexray/volumes/test12/titi
$ sudo ls /var/lib/rexray/volumes/test12/
tata  titi  toto
```

Mount it using docker command

```
$ docker run --rm -it --volume-driver rexray -v test12:/tmp ubuntu
docker: Error response from daemon: chown /var/lib/rexray/volumes/test12: input/output error.
```

rexray logs during docker run : [gist](https://gist.github.com/n1b0r/27584649a2e51d4d2528883a544720b7)

**Comment by alexanderkjeldaas** [comment]
Seems like this issue transmogrified into a docker issue.  However, I have the original issue

```
rexray:
  logLevel: debug
libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: s3fs
  server:
    services:
      cinder:
        driver: cinder
      s3fs:
        driver: s3fs
  integration:
    volume:
      operations:
        mount:
          rootPath: /

cinder:
  authUrl: *
  username: *
  password: *
  tenantName: *
  tenantID: *
  regionName: *
s3fs:
  accessKey: *
  secretKey: *
  options:
  - use_path_request_style
  - allow_other
  - nonempty
```

```
rexray volume mount rexray-test-bucket
ID  Name  Status  Size  Path
FATA[0005] error mounting volume                         error=open rexray-test-bucket: no such file or directory volume=rexray-test-bucket
```
