### ISSUE TITLE
RexRay from a coreos baremetal node to cinder hosted on openstack

### ISSUE THREAD

**Issue by davidrama** [codedellemc/rexray#1057]
# Summary
Hello,
I'm trying to launch rexray on my baremetal server running CoreOS with the cinder driver.
Idea is to create volumes on my openstack.

## Version
Please paste the output of `rexray version`. For example:

REX-Ray
-------
Binary: /opt/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 21:18:02 UTC

## Expected Behavior
Rexray should start on my coreos node

## Actual Behavior
Rexray fail to start with the following message:

error: service startup failed: agent: mod init failed: error initializing instance ID cache

## Configuration Files
```
libstorage:
  service: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 50
        mount:
          rootPath: /data
cinder:
  authURL: http://10.0.45.3:5000/v2.0
  userName: rama
  password: mypass
  tenantName: David
```

## Logs
My logs
https://gist.github.com/davidrama/c72d9ed6ed4d519094a9bb01e97decb2
