### ISSUE TITLE
[Question] Does rexray support multi host volume mounts?

### ISSUE THREAD

**Issue by robvelor** [codedellemc/rexray#343]
Does rexray support multi host volume mounts? For example having a container scale across different hosts sharing the same volume in a swarm cluster.

**Comment by clintonskitson** [comment]
@robvelor Great question. Today REX-Ray was designed to actually ensure safety among many hosts that could *potentially* have access to the same host. This means that it forcefully restricts a single volume to only be available to one host at a time. Following this, if a volume is requested by another host and it is already mapped to a host then we consider *safety* to be critical here (because of XFS/EXT4) where the second host will be denied of the operation.

The `pre-emption` feature ensures that if a second host does request the volume that he is able to forcefully detach it from the original host first, and then bring it to himself. This would simulate a power-off operation of a host attached to a volume where all bits in memory on original host that have not been flushed down is lost. This would support the Swarm use case with a host that fails, and a container trying to be re-scheduled.

What you are describing sounds like you are asking about whether a single volume can simultaneously advertise a single volume in multiple places where that data should be accessible by all hosts through reads only at the same time. We haven't tackled this use case yet, but would be interested to hear more about which applications may make sense for exposing this feature.

**Comment by robvelor** [comment]
@clintonskitson Correct, the last paragraph describes the use case.  Thanks for the clarification :+1:.

**Comment by holms** [comment]
This actually does sounds scary. Why there's no something like blocks? While one container writes to volume, for other IO would be blocked for a while. There's no way to have replica's now, which is in production almost non-usable at all. When one host fails, another one should be alive on another node instantly without any downtime, or else there's no point in distributed volumes. You can't even call it distributed then..

**Comment by holms** [comment]
In my case I can't even start 3 replicas with same volume either preemption is enabled or not it's just fails with this message:

```
tarting container failed: error while mounting volume '': VolumeDriver.Mount: docker-legacy: Mount: mon-whatever-dobs: failed: resource not found
```

**Comment by holms** [comment]
@clintkitson 

```
LIBSTORAGE_INTEGRATION_VOLUME_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=false
```

Which of them do you expect to be true? [Here](https://rexray.readthedocs.io/en/latest/user-guide/schedulers/docker/) it says first one.

**Comment by clintkitson** [comment]
If the volume being mounted is a replica and is completely separate from the original volume then there would be no problem mounting it. The issue is when you try and mount the same exact volume in multiple locations at the same time. 

You can always see the exact flag by running `rexray env | grep PREEMPT`

LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT or `REXRAY_PREEMPT`
https://github.com/rexray/rexray/blob/e8d7a016221ac2ff82e243466cff2d5d214da75d/libstorage/api/types/types_config_integration.go#L5-L18

**Comment by holms** [comment]
Does libstroge config should look like this?

```
libstorage:
   integration:
     volume:
       operations:
         mount:
           preempt: {{ rexray_volume_preempt | lower }}                                                                                                                                                                        
       mount:
         preempt: {{ rexray_volume_preempt | lower }}
       create:
         default:
           size: {{ rexray_volume_size }}
```

Because `LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT` in documentation only specified in one place, it's in mesos configuration, while in docker configuration it's `LIBSTORAGE_INTEGRATION_VOLUME_MOUNT_PREEMPT`

**Comment by clintkitson** [comment]
Yes, that looks right but only the operations.mount.preempt is needed. You can run `rexray env` to verify the configuration is working. 

If `docker` is making replica volume names unique, then REX-Ray would receive these volumes and see them as distinct. But I doubt this is what you're looking for. I believe the replica count should be 1 and you should let Swarm reschedule the container an alternate hosts when it is unavailable. This way you have one container and one volume just get orchestrated to be mounted on other hosts.

**Comment by holms** [comment]
Well this kind of mechanism has drawbacks, I've already had a situation when container died because of http request (jvm actually crashed inside), and rescheduling, I've got more HTTP requests which just ended up in `bad gateway` error :) That's why I want to use container replicas. 

Regarding `operations.mount.preempt` - believe docs should be fixed [here](https://rexray.readthedocs.io/en/latest/user-guide/schedulers/docker/), also as in ansible playbook I had to send PR for you because I'm using `volume.mount.preempt` in there.

**Comment by holms** [comment]
Here you go:

docker-compose.yml:

```
version: '3.6'
services:

    whatever:
      image: nginx
      volumes:
        - "whatever-dobs:/tmp/whatever"
      deploy:
        replicas: 3
        placement:
          constraints:
            - node.role == manager
volumes:
  whatever-dobs:
      driver: rexray

```

On master node

```
root@swarm-master:~# rexray volume ls
ID                                    Name                Status       Size
403b8110-a60b-11e8-b2dd-0242ac114a0a  mon-whatever-dobs   attached     16
```

On manager node:
```
root@swarm-manager-1:~# rexray volume ls
ID                                    Name                Status       Size
403b8110-a60b-11e8-b2dd-0242ac114a0a  mon-whatever-dobs   unavailable  16
```

On manager2 node:
```
root@swarm-manager-0:~# rexray volume ls
ID                                    Name                Status       Size
403b8110-a60b-11e8-b2dd-0242ac114a0a  mon-whatever-dobs   unavailable  16

```

pre-empt is enabled on all nodes:
```
holms@debian ~/D/c/l/a/prod> env ANSIBLE_TF_DIR=./terraform env ANSIBLE_CONFIG=ansible/ansible.cfg ansible swarm-prod -i ./ansible/terraform.py  -a "rexray env" | grep PREEMPT
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
LIBSTORAGE_INTEGRATION_VOLUME_OPERATIONS_MOUNT_PREEMPT=true
```

Is this expected behavior?
