### ISSUE TITLE
ERROR initializing driver driverName=ec2 error.provider=ec2 no storage driver initialized.

### ISSUE THREAD

**Issue by gufranmmu** [codedellemc/rexray#430]
eucatools works
s3cmd works
with provided endpoint-url:
`aws --endpoint-url http://compute.esclor86.eecloud.net:8773/  ec2 describe-volumes` works as well

I used rex-ray ansible to install rexray stable version

but, rexray gives error: no storage driver initialized when running without -f and
then I started with **"rexray service -f -l debug"** command and I get the following error:
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[ec2] volumeDrivers=[docker]
INFO[0000] os driver initialized                         moduleName=default-docker provider=linux
DEBU[0000] error initializing driver                     driverName=ec2 error.provider=ec2
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName=default-docker provider=docker size= volumeRootPath=/data volumeType=
DEBU[0000] checking volume path cache setting            pathCache=true
INFO[0000] vdm.List                                      driverName=docker moduleName=default-docker
INFO[0000] listing volumes                               driverName=docker moduleName=default-docker
ERRO[0000] default module(s) failed to start
INFO[0000] service sent registered modules start signals
ERRO[0000] service initialized failed
INFO[0000] error initializing driver                     m=&{r:0xc820305e00 name:default-docker addr:unix:///run/docker/plugins/rexray.sock desc:The default docker module.} m.r=&{Config:0xc8203194c0 OS:0xc820367330 Volume:0xc820319f20 Storage:0xc820367340 Context:default-docker drivers:map[VMAX:0xc82031c0f0 XtremIO:0xc820305ec0 linux:0xc82002c3b8 ec2:0xc820312de0 docker:0xc82002c3c0 Openstack:0xc820305e60 ScaleIO:0xc820312ae0 virtualbox:0xc8203195c0 gce:0xc82030b600 Isilon:0xc82031ba60 Rackspace:0xc82030b4c0]}

**¨Credentials are correct. Here is my config:**

```
rexray:
  logLevel: warn
  osDrivers:
  - linux
  volumeDrivers:
  - docker
  storageDrivers:
  - ec2
aws:
  accessKey: AAG552VA2CCJ3W3
  secretKey: aLnmezFwLDCKccGm3ILV5LIM1TER2o6b
  region: http://compute.esclor86.eecloud.net:8773/
  ec2Url: http://compute.esclor86.eecloud.net:8773/
#  ec2URL: http://compute.esclor86.eecloud.net:8773/
#  endpointUrl: compute.esclor86.eecloud.net:8773
#  endpointURL: http://compute.esclor86.eecloud.net:8773/
  url: http://compute.esclor86.eecloud.net:8773/

```

**[root@mesos-slave-1 ~]# rexray env | grep -i docker**
DOCKER_AVAILABILITYZONE=
DOCKER_VOLUMETYPE=
REXRAY_MODULES_DEFAULT-DOCKER_DISABLED=false
REXRAY_MODULES_DEFAULT-DOCKER_HOST=unix:///run/docker/plugins/rexray.sock
REXRAY_MODULES_DEFAULT-DOCKER_DESC=The default docker module.
REXRAY_VOLUMEDRIVERS=docker
DOCKER_IOPS=
DOCKER_SIZE=
REXRAY_MODULES_DEFAULT-DOCKER_SPEC=/etc/docker/plugins/rexray.spec
DOCKER_FSTYPE=
REXRAY_MODULES_DEFAULT-DOCKER_TYPE=docker

ctrl + f "configure aws cli": https://support.eucalyptus.com/hc/en-us/articles/200844844-Usage-of-AWS-CLI-with-Eucalyptus
