### ISSUE TITLE
rexray advertises ebs storage, but doesn't implement it?!

### ISSUE THREAD

**Issue by kapilt** [codedellemc/rexray#539]
i'm not seeing the support through any of the dependencies of rexray (libstorage) etc, just EFS re aws specific storage (per https://github.com/emccode/libstorage/tree/master/drivers/storage)  Am I missing something or are the docs/marketing wrong wrt to the current implementation and EBS support?

**Comment by kacole2** [comment]
It's on the first page of the docs for REX-Ray. EBS is supported in v0.3.3. The new architecture in 0.4.X relies on libStorage where it hasn't yet been refactored.

**Comment by kapilt** [comment]
First page would be the readme, which still references ebs support

**Comment by kacole2** [comment]
@kapilt understood. The new version (0.4.X) doesn't add more **functionality**. This is strictly a version rev to move to a new architecture using (libStorage)[https://github.com/emccode/libstorage) as the workhorse under the covers. This move was done to satisfy growth requirements and the ability to use libStorage in more projects. In addition, the ability to add more storage platforms as libStorage components. At this moment, v0.3.3 is in a stable state and supports Amazon EBS. Here is the issue for EBS with libStorage and as you can see progress is being made https://github.com/emccode/libstorage/issues/183.

At this time, we still recommend using v0.3.3 (git commit id [b30fb870b5b94cd8368824460ad020bfcf20be3a](https://github.com/emccode/rexray/commit/b30fb870b5b94cd8368824460ad020bfcf20be3a))

installation:
```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.3.3
```

rexray `config.yml`
```
rexray:
  logLevel: warn
  storageDrivers:
  - ec2
aws:
  accessKey: mykey
  secretKey: secret key
```

Pre-emption for HA works as well with this configuration file:
```
rexray:
  logLevel: warn
  storageDrivers:
  - ec2
  volume:
    mount:
      preempt: true
aws:
  accessKey: mykey
  secretKey: mysecretkey
```
