### ISSUE TITLE
Docker volume integration attaches a volume when status is unavailable

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#659]
When launching a container with the REX-Ray docker volume integration, an unavailable volume should not be able to be used unless preemptive mounting is enabled. What I am seeing is that this is not happening. Docker is launching a container with the unavailable volume successfully - it is preemptively taking the volume when it shouldn't be able to.

test_vol01 is attached to node01:
```
[root@node01 ~]# rexray volume ls
ID                Name        Status       Size
925def880000000a  vol01       attached     16
```
status of vol01 is unavailable on node02:
```
[root@node02 ~]# rexray volume ls
ID                Name        Status       Size
925def880000000a  vol01       unavailable  16
```

rexray volume attach command fails with vol01 on node02:
```
[root@node02 ~]# rexray volume attach vol01
ID  Name  Status  Size
FATA[0001] error attaching volume                        error.status=500 volume=vol01
```

docker run command succeeds in starting container with vol01 on node02:
```
[root@node02 ~]# docker run -d --name redis --volume-driver rexray --volume vol01:/data redis
4c87e0c549778e519995bb9fe9c24d1b9864d5f00e1a6280e0d2bca271be079c
```

REX-Ray Version:
```
REX-Ray
-------
Binary: /usr/bin/rexray
SemVer: 0.6.3
OsArch: Linux-x86_64
Branch: v0.6.3
Commit: 69b1f5c2d86a2103c792bec23b5855babada1c0a
Formed: Wed, 07 Dec 2016 15:22:14 PST

libStorage
----------
SemVer: 0.3.5
OsArch: Linux-x86_64
Branch: v0.6.3
Commit: 456dd68123dd6b49da0275d9bbabd6c800583f61
Formed: Wed, 07 Dec 2016 15:21:36 PST
```

REX-Ray Config:
```
libstorage:
  integration:
    volume:
      operations:
        create:
          default:
            fsType: xfs
        mount:
          preempt: true
  service: scaleio
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://10.50.10.200/api
          insecure: true
          userName: admin
          password: ------
          systemName: scaleio
          protectionDomainName: default
          storagePoolName: default
```
