### ISSUE TITLE
Multiple instances of Rexray plugin for ScaleIO

### ISSUE THREAD

**Issue by rafakei** [codedellemc/rexray#685]
Hi, Gurus

An SDC can accept volumes from different ScaleIO systems and protection domains. Right now, Rexray only allows specifying a storage pool. Since release 0.9 is still months away on the roadmap, a temporary measure would be running multiple instances of Rexray plugin with a single docker engine, which requires renaming a Rexray plugin to rexray1, rexray2, and so on. Could you please point me to the right direction about what I should change to achieve that in the current code?

Thanks

**Comment by kacole2** [comment]
@rafakei . we're all back from our holiday break. This can be done today using [Multiple Service](http://libstorage.readthedocs.io/en/stable/user-guide/config/#multiple-services) from libStorage. libStorage is already embedded inside of REX-Ray. So having multiple ScaleIO systems is easy without having to run multiple instances of REX-Ray. When using an advanced configuration such as this, the name of the volume driver becomes arbitrary.

Here's a normal ScaleIO with REX-Ray configuration
```
libstorage:
  service: scaleio
  integration:
    volume:
      operations:
        mount:
          preempt: true
scaleio:
  insecure: true
  thinOrThick: ThinProvisioned
  endpoint: https://scaleio.mycorp.com/api
  userName: admin
  password: scaleio123
  systemName: cluster1
  protectionDomainName: pdomain
  useCerts: true
  storagePoolName: pool1
```

and you can use docker with:
```
$ docker run -d --volume-driver=rexray -v test01:/test01 busybox
```

Using an advanced configuration might look something like this (note, I have not personally tested this so please come back to the issue so we can properly debug your `config.yml` file)
```
libstorage:
  server:
    services:
      scaleio-system-01:
        driver: scaleio
        scaleio:
          endpoint: https://gateway_ip/api
          insecure: true
          userName: username
          password: password
          systemName: tenantName
          protectionDomainName: protectionDomainName
          storagePoolName: storagePoolName
        integration:
          volume:
            operations:
              mount:
                preempt: true
      scaleio-system-02:
        driver: scaleio
        scaleio:
          endpoint: https://gateway_ip/api
          insecure: true
          userName: username
          password: password
          systemName: tenantName
          protectionDomainName: protectionDomainName
          storagePoolName: storagePoolName
        integration:
          volume:
            operations:
              mount:
                preempt: true
```

and you can use docker with:
```
$ docker run -d --volume-driver=scaleio-system-01 -v test01:/test01 busybox
$ docker run -d --volume-driver=scaleio-system-02 -v test01:/test01 busybox
```

The name of the volume driver becomes whatever is specified in the advanced configuration. Only one instance of REX-Ray is running but can take care of multiple storage endpoints. The names of the volumes can be identical since they are running on two separate instances.

hope that helps

**Comment by rafakei** [comment]
@kacole2 good catch! 

rexray volume ls/create all works, but docker volume ls/create fails. Please help. 

	libstorage:
	  server:
		services:
		  scaleio-system-01:
			driver: scaleio
			scaleio:
			  endpoint: https://10.32.197.150/api
			  insecure: true
			  thinOrThick: ThinProvisioned
			  userName: admin
			  password: ABcd1234
			  systemName: sio4
			  protectionDomainName: PD1
			  storagePoolName: SP1
			integration:
			  volume:
				operations:
				  create:
					default:
					  fsType: xfs
					  size: 8
				  mount:
					preempt: true
		  scaleio-system-02:
			driver: scaleio
			scaleio:
			  endpoint: https://10.32.197.170/api
			  insecure: true
			  thinOrThick: ThinProvisioned
			  userName: admin
			  password: ABcd1234
			  systemName: sio5
			  protectionDomainName: PD1
			  storagePoolName: SP1
			integration:
			  volume:
				operations:
				  create:
					default:
					  fsType: xfs
					  size: 8
				  mount:
					preempt: true
					
	# rexray -s scaleio-system-01 volume ls
	ID                Name           Status       Size
	b138681f00000000  VASA-database  unavailable  8
	b139799200000001  vol1           available    16

	# rexray volume ls
	FATA[0000] http error                                    status=404

	# docker volume ls
	list rexray: VolumeDriver.List: {"Error":"http error"}

	DRIVER              VOLUME NAME

**Comment by rafakei** [comment]
@kacole2 

No need of two SIO systems, a single system with below config.yml syntax will show the same problem:

	libstorage:
	  server:
		services:
		  scaleio-system-01:
			driver: scaleio
			scaleio:
			  endpoint: https://10.32.197.150/api
			  insecure: true
			  thinOrThick: ThinProvisioned
			  userName: admin
			  password: ABcd1234
			  systemName: sio4
			  protectionDomainName: PD1
			  storagePoolName: SP1
			integration:
			  volume:
				operations:
				  create:
					default:
					  fsType: xfs
					  size: 8
				  mount:
					preempt: true

**Comment by rafakei** [comment]
`Jan  5 00:57:53 shaoye rexray: time="2017-01-05T00:57:53+08:00" level=error msg="/VolumeDriver.List: error listing volumes" error.status=404 host="unix:///var/run/libstorage/924989802.sock" time=1483549073956
Jan  5 00:57:53 shaoye dockerd: time="2017-01-05T00:57:53.956838074+08:00" level=warning msg="list rexray: VolumeDriver.List: {\"Error\":\"http error\"}\n"
`

**Comment by rafakei** [comment]
# rexray volume ls
	FATA[0000] http error                                    status=404

	# rexray volume ls -l debug
	INFO[0000] updated log level                             logLevel=debug
	DEBU[0000] os.args                                       time=1483549199086 val=[rexray volume ls -l debug]
	DEBU[0000] activating libStorage                         cmd=ls time=1483549199086
	DEBU[0000] read spec file                                host=unix:///var/run/libstorage/924989802.sock path=/var/run/rexray/rexray.spec time=1483549199088
	DEBU[0000] is local unix server active                   sock=/var/run/libstorage/924989802.sock time=1483549199088
	DEBU[0000] set host in context                           host=unix:///var/run/libstorage/924989802.sock time=1483549199088
	DEBU[0000] set host in config                            host=unix:///var/run/libstorage/924989802.sock time=1483549199088
	DEBU[0000] not starting embedded server; already running  host=unix:///var/run/libstorage/924989802.sock time=1483549199088
	DEBU[0000] created scoped scope                          new=libstorage.client parentScopes=rexray,
	INFO[0000] configured logging                            host=unix:///var/run/libstorage/924989802.sock libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug time=1483549199118
	DEBU[0000] got configured host address                   host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199122
	INFO[0000] created libStorage client                     clientType=integration disableKeepAlive=false enableInstanceIDHeaders=true enableLocalDevicesHeaders=true host=unix:///var/run/libstorage/924989802.sock logRequests=false logResponses=false lsxPath=/var/lib/libstorage/lsx-linux service= storageDriver=libstorage time=1483549199130
	INFO[0000] lsx lock file path                            host=unix:///var/run/libstorage/924989802.sock path=/var/run/libstorage/lsx.lock service= storageDriver=libstorage time=1483549199130
	INFO[0000] initializing executors cache                  host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199132
	DEBU[0000] updating executor                             host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199132
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199133
	DEBU[0000] executor exists, getting local checksum       host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199133
	DEBU[0000] getting executor checksum                     host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199133
	DEBU[0000] got local executor checksum                   host=unix:///var/run/libstorage/924989802.sock localChecksum=6bf696594c988cb1707df70f811d9532 service= storageDriver=libstorage time=1483549199153
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199153
	INFO[0000] initializing supported cache                  host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199153
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199153 txCR=1483549199 txID=f7ae1a03-ea0a-4605-4732-d7624b50628c
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199198 txCR=1483549199 txID=f7ae1a03-ea0a-4605-4732-d7624b50628c
	DEBU[0000] cached supported flag                         host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage supported=true time=1483549199198 txCR=1483549199 txID=f7ae1a03-ea0a-4605-4732-d7624b50628c
	INFO[0000] initializing instance ID cache                host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199198
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199198 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199249 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	DEBU[0000] sending instanceID in API.InstanceInspect call  host=unix:///var/run/libstorage/924989802.sock instanceID=scaleio=,,IkUwNjcyQzk5LUYwMDQtNDVCNi04MTg0LUEzOEVBQkI4ODVDQSI= server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199249 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	DEBU[0000] received instanceID from API.InstanceInspect call  host=unix:///var/run/libstorage/924989802.sock instanceID=scaleio=,,IkUwNjcyQzk5LUYwMDQtNDVCNi04MTg0LUEzOEVBQkI4ODVDQSI= server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199257 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	DEBU[0000] cached instanceID                             host=unix:///var/run/libstorage/924989802.sock instanceID=scaleio=9675b0c100000007 server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199257 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	DEBU[0000] xli instanceID success                        host=unix:///var/run/libstorage/924989802.sock instanceID=scaleio=9675b0c100000007 server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199257 txCR=1483549199 txID=cb6fe2f5-de8b-4ea6-64f1-cbea3e553d4c
	INFO[0000] initializing supported cache                  host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-02 storageDriver=libstorage time=1483549199257
	INFO[0000] initializing instance ID cache                host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service=scaleio-system-02 storageDriver=libstorage time=1483549199258
	INFO[0000] successefully dialed libStorage server        host=unix:///var/run/libstorage/924989802.sock server=mire-song-uz service= storageDriver=libstorage time=1483549199258
	INFO[0000] storage driver initialized                    host=unix:///var/run/libstorage/924989802.sock service= storageDriver=libstorage time=1483549199258
	INFO[0000] os driver initialized                         host=unix:///var/run/libstorage/924989802.sock osDriver=linux service= storageDriver=libstorage time=1483549199259
	INFO[0000] docker integration driver successfully initialized  host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker libstorage.integration.volume.operations.create.default.IOPS= libstorage.integration.volume.operations.create.default.availabilityZone= libstorage.integration.volume.operations.create.default.fsType=ext4 libstorage.integration.volume.operations.create.default.size=16 libstorage.integration.volume.operations.create.default.type= libstorage.integration.volume.operations.create.implicit=true libstorage.integration.volume.operations.mount.path=/var/lib/libstorage/volumes libstorage.integration.volume.operations.mount.rootPath=/data osDriver=linux service= storageDriver=libstorage time=1483549199269
	INFO[0000] path cache initializion disabled              host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux service= storageDriver=libstorage time=1483549199270
	INFO[0000] libStorage integration driver successfully initialized  host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker libstorage.integration.volume.operations.create.disable=false libstorage.integration.volume.operations.mount.preempt=false libstorage.integration.volume.operations.path.cache.async=true libstorage.integration.volume.operations.path.cache.enabled=false libstorage.integration.volume.operations.remove.disable=false libstorage.integration.volume.operations.unmount.ignoreusedcount=false osDriver=linux service= storageDriver=libstorage time=1483549199276
	INFO[0000] integration driver initialized                host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux service= storageDriver=libstorage time=1483549199276
	INFO[0000] created libStorage client                     host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux service= storageDriver=libstorage time=1483549199276
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199276 txCR=1483549199 txID=a64e530e-6893-4783-6ee3-a708998ca113
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199326 txCR=1483549199 txID=a64e530e-6893-4783-6ee3-a708998ca113
	DEBU[0000] xli localdevices success                      host=unix:///var/run/libstorage/924989802.sock integrationDriver=docker osDriver=linux server=mire-song-uz service=scaleio-system-01 storageDriver=libstorage time=1483549199326 txCR=1483549199 txID=a64e530e-6893-4783-6ee3-a708998ca113
	FATA[0000] http error                                    status=404

**Comment by rafakei** [comment]
Last login: Thu Jan  5 00:57:31 2017 from 10.32.196.48
	[root@shaoye ~]# rexray -s scaleio-system-01 volume ls
	ID                Name           Status       Size
	b138681f00000000  VASA-database  unavailable  8
	b139799700000001  vol1           attached     8
	[root@shaoye ~]# rexray -s scaleio-system-01 volume ls -l debug
	INFO[0000] updated log level                             logLevel=debug
	DEBU[0000] os.args                                       time=1483550112458 val=[rexray -s scaleio-system-01 volume ls -l debug]
	DEBU[0000] activating libStorage                         cmd=ls time=1483550112458
	DEBU[0000] read spec file                                host=unix:///var/run/libstorage/989658339.sock path=/var/run/rexray/rexray.spec time=1483550112459
	DEBU[0000] is local unix server active                   sock=/var/run/libstorage/989658339.sock time=1483550112460
	DEBU[0000] set host in context                           host=unix:///var/run/libstorage/989658339.sock time=1483550112460
	DEBU[0000] set host in config                            host=unix:///var/run/libstorage/989658339.sock time=1483550112460
	DEBU[0000] not starting embedded server; already running  host=unix:///var/run/libstorage/989658339.sock time=1483550112460
	DEBU[0000] created scoped scope                          new=libstorage.client parentScopes=rexray,
	INFO[0000] configured logging                            host=unix:///var/run/libstorage/989658339.sock libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug time=1483550112489
	DEBU[0000] got configured host address                   host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112492
	INFO[0000] created libStorage client                     clientType=integration disableKeepAlive=false enableInstanceIDHeaders=true enableLocalDevicesHeaders=true host=unix:///var/run/libstorage/989658339.sock logRequests=false logResponses=false lsxPath=/var/lib/libstorage/lsx-linux service=scaleio-system-01 storageDriver=libstorage time=1483550112500
	INFO[0000] lsx lock file path                            host=unix:///var/run/libstorage/989658339.sock path=/var/run/libstorage/lsx.lock service=scaleio-system-01 storageDriver=libstorage time=1483550112500
	INFO[0000] initializing executors cache                  host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112502
	DEBU[0000] updating executor                             host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112502
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112503
	DEBU[0000] executor exists, getting local checksum       host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112503
	DEBU[0000] getting executor checksum                     host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112503
	DEBU[0000] got local executor checksum                   host=unix:///var/run/libstorage/989658339.sock localChecksum=6bf696594c988cb1707df70f811d9532 service=scaleio-system-01 storageDriver=libstorage time=1483550112523
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112523
	INFO[0000] initializing supported cache                  host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112523
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112523 txCR=1483550112 txID=b19197c3-28b5-4b70-4273-eaf29d39faaa
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112583 txCR=1483550112 txID=b19197c3-28b5-4b70-4273-eaf29d39faaa
	DEBU[0000] cached supported flag                         host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage supported=true time=1483550112583 txCR=1483550112 txID=b19197c3-28b5-4b70-4273-eaf29d39faaa
	INFO[0000] initializing instance ID cache                host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112583
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112583 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112638 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	DEBU[0000] sending instanceID in API.InstanceInspect call  host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=,,IkUwNjcyQzk5LUYwMDQtNDVCNi04MTg0LUEzOEVBQkI4ODVDQSI= server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112639 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	DEBU[0000] received instanceID from API.InstanceInspect call  host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=,,IkUwNjcyQzk5LUYwMDQtNDVCNi04MTg0LUEzOEVBQkI4ODVDQSI= server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112647 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	DEBU[0000] cached instanceID                             host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=9675b0c100000007 server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112647 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	DEBU[0000] xli instanceID success                        host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=9675b0c100000007 server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112647 txCR=1483550112 txID=bfbe0021-18f6-4fe0-6646-31f06c3857dc
	INFO[0000] initializing supported cache                  host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-02 storageDriver=libstorage time=1483550112647
	INFO[0000] initializing instance ID cache                host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-02 storageDriver=libstorage time=1483550112647
	INFO[0000] successefully dialed libStorage server        host=unix:///var/run/libstorage/989658339.sock server=citrine-toucan-tz service=scaleio-system-01 storageDriver=libstorage time=1483550112647
	INFO[0000] storage driver initialized                    host=unix:///var/run/libstorage/989658339.sock service=scaleio-system-01 storageDriver=libstorage time=1483550112647
	INFO[0000] os driver initialized                         host=unix:///var/run/libstorage/989658339.sock osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112648
	INFO[0000] docker integration driver successfully initialized  host=unix:///var/run/libstorage/989658339.sock integrationDriver=docker libstorage.integration.volume.operations.create.default.IOPS= libstorage.integration.volume.operations.create.default.availabilityZone= libstorage.integration.volume.operations.create.default.fsType=ext4 libstorage.integration.volume.operations.create.default.size=16 libstorage.integration.volume.operations.create.default.type= libstorage.integration.volume.operations.create.implicit=true libstorage.integration.volume.operations.mount.path=/var/lib/libstorage/volumes libstorage.integration.volume.operations.mount.rootPath=/data osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112658
	INFO[0000] path cache initializion disabled              host=unix:///var/run/libstorage/989658339.sock integrationDriver=docker osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112659
	INFO[0000] libStorage integration driver successfully initialized  host=unix:///var/run/libstorage/989658339.sock integrationDriver=docker libstorage.integration.volume.operations.create.disable=false libstorage.integration.volume.operations.mount.preempt=false libstorage.integration.volume.operations.path.cache.async=true libstorage.integration.volume.operations.path.cache.enabled=false libstorage.integration.volume.operations.remove.disable=false libstorage.integration.volume.operations.unmount.ignoreusedcount=false osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112665
	INFO[0000] integration driver initialized                host=unix:///var/run/libstorage/989658339.sock integrationDriver=docker osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112665
	INFO[0000] created libStorage client                     host=unix:///var/run/libstorage/989658339.sock integrationDriver=docker osDriver=linux service=scaleio-system-01 storageDriver=libstorage time=1483550112665
	DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=9675b0c100000007 integrationDriver=docker osDriver=linux server=citrine-toucan-tz service=scaleio-system-02 storageDriver=libstorage time=1483550112665 txCR=1483550112 txID=923a5579-bfd6-459b-44da-231c6d26f5d4
	DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=9675b0c100000007 integrationDriver=docker osDriver=linux server=citrine-toucan-tz service=scaleio-system-02 storageDriver=libstorage time=1483550112717 txCR=1483550112 txID=923a5579-bfd6-459b-44da-231c6d26f5d4
	DEBU[0000] xli localdevices success                      host=unix:///var/run/libstorage/989658339.sock instanceID=scaleio=9675b0c100000007 integrationDriver=docker osDriver=linux server=citrine-toucan-tz service=scaleio-system-02 storageDriver=libstorage time=1483550112717 txCR=1483550112 txID=923a5579-bfd6-459b-44da-231c6d26f5d4
	DEBU[0000] built output template                         host=unix:///var/run/libstorage/989658339.sock template={{define "printVolumeFields"}}{{.ID}}  {{.Name}}       {{.AttachmentState | printAttState}}  {{.Size}}{{end}}{{define "printEncVolumeFields"}}{{.ID}} {{.Name}}       {{.AttachmentState | printAttState}}    {{.Size}}       {{.Encrypted}}{{end}}{{define "printEncVolumeWithPathFields"}}{{.ID}}   {{.Name}}      {{.Volume.AttachmentState | printAttState}}     {{.Size}}       {{.Encrypted}}  {{.Path}}{{end}}{{define "printInstanceFields"}}{{.InstanceID.ID}}      {{.Name}}       {{.ProviderName}}       {{.Region}}{{end}}{{define "printServiceFields"}}{{.Name}}     {{.Driver.Name}}{{end}}{{define "printObject"}}{{printf "%v" .}}{{end}}{{define "printJSON"}}{{. | json}}{{end}}{{define "printPrettyJSON"}}{{. | jsonp}}{{end}}{{define "printSnapshotFields"}}{{.ID}}        {{.Name}}       {{.Status}}     {{.VolumeID}}{{end}}{{define "printMountFields"}}{{.ID}}        {{.Source}}     {{.MountPoint}}{{end}}{{define "printStringSlice"}}{{.}}{{end}}{{define "printVolumeID"}}{{.ID}}{{end}}{{define "printVolumeWithPathFields"}}{{.ID}}   {{.Name}}       {{.Volume.AttachmentState | printAttState}}     {{.Size}}       {{.Path}}{{end}}ID     Name    Status  Size
	{{range sort .D "Name" }}{{template "printVolumeFields" .}}
	{{end}} time=1483550112746
	ID                Name           Status       Size
	b138681f00000000  VASA-database  unavailable  8
	b139799700000001  vol1           attached     8
	DEBU[0000] waiting until libStorage is stopped           host=unix:///var/run/libstorage/989658339.sock time=1483550112747
	DEBU[0000] done waiting on err chan; err chan is nil     host=unix:///var/run/libstorage/989658339.sock time=1483550112747
	DEBU[0000] completed cli execution                       time=1483550112747
	INFO[0000] exiting process                               time=1483550112747
	DEBU[0000] completed onExit at end of program            time=1483550112747
	[root@shaoye ~]#

**Comment by rafakei** [comment]
It seems "rexray volume ls" does not send "instanceID" while "waiting/signaling on executor lock". Please help troubleshoot it. 

	# rexray version
	REX-Ray
	-------
	Binary: /usr/bin/rexray
	SemVer: 0.6.3
	OsArch: Linux-x86_64
	Branch: v0.6.3
	Commit: 69b1f5c2d86a2103c792bec23b5855babada1c0a
	Formed: Thu, 08 Dec 2016 07:22:14 CST

	libStorage
	----------
	SemVer: 0.3.5
	OsArch: Linux-x86_64
	Branch: v0.6.3
	Commit: 456dd68123dd6b49da0275d9bbabd6c800583f61
	Formed: Thu, 08 Dec 2016 07:21:36 CST
	# docker -v
	Docker version 1.12.5, build 7392c3b

**Comment by cduchesne** [comment]
@kacole2 @rafakei - looking into this now

**Comment by kacole2** [comment]
@cduchesne @rafakei --- i need to take the blame on giving you an incorrect config. Please take a look at [REX-Ray Modules](http://rexray.readthedocs.io/en/stable/user-guide/config/#example-with-modules) for getting a correct config up and running.

**Comment by akutz** [comment]
Hi @rafakei,

@cduchesne is handling this, but I wanted to say _hello_ and offer an example config based on the one @kacole2 provided above:

```yaml
libstorage:
  integration:
    volume:
      operations:
        mount:
          preempt: true
  server:
    services:
      scaleio-system-01:
        driver: scaleio
        scaleio:
          endpoint: https://gateway_ip/api
          insecure: true
          userName: username
          password: password
          systemName: tenantName
          protectionDomainName: protectionDomainName
          storagePoolName: storagePoolName
      scaleio-system-02:
        driver: scaleio
        scaleio:
          endpoint: https://gateway_ip/api
          insecure: true
          userName: username
          password: password
          systemName: tenantName
          protectionDomainName: protectionDomainName
          storagePoolName: storagePoolName
rexray:
  modules:
    default-docker:
      type: docker
      desc: The default docker module.
      host: unix:///run/docker/plugins/scaleio01.sock
      libstorage:
        service: scaleio-system-01
    scaleio02:
      type: docker
      desc: The second docker module.
      host: unix:///run/docker/plugins/scaleio02.sock
      libstorage:
        service: scaleio-system-02
```

So let's note a few things:

* The `libstorage.integration.volume.operations.mount.preempt` property was moved to the root of the config as it was the same value for each service. Additionally, that value isn't specific to a service -- it's a client-side value. You *could* relocate it, but I'll tell you where later.

* Defining two services doesn't tell Docker how to talk to them. The two services are libStorage services. Docker still needs Volume Driver endpoints defined. That is what the REX-Ray [module configuration](http://rexray.readthedocs.io/en/stable/user-guide/config/#example-with-modules) does. It lets you define multiple Docker endpoints and connect them with specific libStorage services as in the above config.

* A module config is also where you could define custom client options. For example, here is a config snippet from above where each module defines a different value for the `libstorage.integration.volume.operations.mount.preempt` property:

```yaml
rexray:
  modules:
    default-docker:
      type: docker
      desc: The default docker module.
      host: unix:///run/docker/plugins/scaleio01.sock
      libstorage:
        service: scaleio-system-01
          integration:
            volume:
              operations:
                mount:
                  preempt: false
    scaleio02:
      type: docker
      desc: The second docker module.
      host: unix:///run/docker/plugins/scaleio02.sock
      libstorage:
        service: scaleio-system-02
          integration:
            volume:
              operations:
                mount:
                  preempt: true
```

Note in the above example the first module sets the `libstorage.integration.volume.operations.mount.preempt` property to `false` while the second property sets it to `true`.

**Comment by akutz** [comment]
Hi @rafakei,

By the way, you could also omit the dual ScaleIO configs from the libStorage services, overriding only the different values. For example, let's say the only difference is the protection domain and storage pool:

```yaml
libstorage:
  integration:
    volume:
      operations:
        mount:
          preempt: true
  server:
    services:
      scaleio-system-01:
        driver: scaleio
        scaleio:
          protectionDomainName: Domain1
          storagePoolName: Pool1
      scaleio-system-02:
        driver: scaleio
        scaleio:
          protectionDomainName: Domain2
          storagePoolName: Pool2
scaleio:
  endpoint: https://gateway_ip/api
  insecure: true
  userName: username
  password: password
  systemName: tenantName
  protectionDomainName: protectionDomainName
  storagePoolName: storagePoolName
rexray:
  modules:
    default-docker:
      type: docker
      desc: The default docker module.
      host: unix:///run/docker/plugins/scaleio01.sock
      libstorage:
        service: scaleio-system-01
    scaleio02:
      type: docker
      desc: The second docker module.
      host: unix:///run/docker/plugins/scaleio02.sock
      libstorage:
        service: scaleio-system-02
```

The above example should also work, and it reduces the duplication of the config data except where necessary to provide scoped values.
