### ISSUE TITLE
Problem mounting with docker volume plugin (ScaleIO)

### ISSUE THREAD

**Issue by lucasyvas** [codedellemc/rexray#706]
Help wanted!

DCOS: 1.8
REX-Ray: 0.3.3
Docker: 1.11.2
ScaleIO: 2

Here's my REX-Ray config.yml on each host

```
rexray:
  storageDrivers:
  - scaleio
  volume:
    mount:
      preempt: true
    unmount:
      ignoreusedcount: true
    remove:
      disable: true
docker:
  size: 56
scaleio:
  endpoint: https://10.168.147.137/api
  apiVersion: "2.0"
  insecure: true
  useCerts: false
  userName: admin
  password: XXXXXXXXXX
  systemID: 502e90e16772c3b9
  protectionDomainID: 51640e0b00000000
  storagePoolID: 3ed68b6500000000
  thinOrThick: ThickProvisioned
```

When I deploy a docker container, I can see it successfully creates the volume by running `rexray volume` on one of the hosts:

```
- name: my-test-vol
  volumeid: 80ae0ba100000001
  availabilityzone: Sjc03-CLS-001
  status: ""
  volumetype: SSD
  iops: 0
  size: "56"
  networkname: ""
  attachments:
  - volumeid: 80ae0ba100000001
    instanceid: "9618993800000006"
    devicename: ""
    status: ""
```

However, the container will not deploy because it is failing to mount the volume. This is what I see when running `cat /var/log/rexray/rexray.log`:

```
time="2017-01-24T22:23:01Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-24T22:23:01Z" level=error msg="device or resource busy" 
time="2017-01-24T22:25:48Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="error waiting on volume to mount" 
time="2017-01-24T22:25:48Z" level=error msg="error waiting on volume to mount" inner.provider=ScaleIO instanceId=9618993700000005 moduleName=default-docker provider=ScaleIO runAsync=false volumeId=80ae0ba200000002
```

And on another host:

```
time="2017-01-25T00:10:05Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-25T00:10:05Z" level=error msg="device or resource busy" 
time="2017-01-25T00:10:12Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="no device name returned" 
time="2017-01-25T00:10:12Z" level=error msg="no device name returned" 
time="2017-01-25T00:10:13Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-25T00:10:13Z" level=error msg="device or resource busy" 
time="2017-01-25T00:10:20Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="no device name returned" 
time="2017-01-25T00:10:20Z" level=error msg="no device name returned" 
time="2017-01-25T00:10:21Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-25T00:10:21Z" level=error msg="device or resource busy" 
time="2017-01-25T00:10:29Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="no device name returned" 
time="2017-01-25T00:10:29Z" level=error msg="no device name returned" 
time="2017-01-25T00:10:30Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-25T00:10:30Z" level=error msg="device or resource busy" 
time="2017-01-25T00:10:38Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="no device name returned" 
time="2017-01-25T00:10:38Z" level=error msg="no device name returned" 
time="2017-01-25T00:10:39Z" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="device or resource busy" 
time="2017-01-25T00:10:39Z" level=error msg="device or resource busy" 
time="2017-01-25T00:17:57Z" level=error msg="/VolumeDriver.Get: error getting volume" error="No volumes returned" 
time="2017-01-25T00:17:57Z" level=error msg="No volumes returned" 
time="2017-01-25T00:22:32Z" level=error msg="/VolumeDriver.Get: error getting volume" error="No volumes returned" 
time="2017-01-25T00:22:32Z" level=error msg="No volumes returned" 
time="2017-01-25T00:22:32Z" level=error msg="/VolumeDriver.Get: error getting volume" error="No volumes returned" 
time="2017-01-25T00:22:32Z" level=error msg="No volumes returned" 
time="2017-01-25T00:24:48Z" level=error msg="/VolumeDriver.Mount: error mounting volume" error="read /dev/scinia: input/output error" 
time="2017-01-25T00:24:48Z" level=error msg="read /dev/scinia: input/output error"
```
