### ISSUE TITLE
FlexRex adapter script does not display proper error

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/rexray#716]
# Summary
The FlexRex adapter script does not return proper error string when failure occurs in REX-Ray.

# Bug Reports
When an error occurs in REX-Ray, it appears that the error is not being properly reported back to the the FlexVolume plugin to be logged properly in Kubernetes.

## Version
Please paste the output of `rexray version`. For example:

```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a20a838ca70838a914b632637398824fcb10d0db
Formed: Mon, 23 Jan 2017 10:14:32 EST

libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 10:14:12 EST
```

## Expected Behavior
For instance, when attaching a non-existent volume, the rexray log emits the following error:

```
time="2017-02-08T15:11:39-05:00" level=fatal msg="no volumes found"
```  

## Actual Behavior
The error string displayed in Kubernetes does not reflect what happened in REX-Ray as shown in the following output:
```
MountVolume.SetUp failed for volume "rexray/flexrex/1f871e4d-ee38-11e6-969d-080027859f43-vol-0" (spec.Name: "vol-0") pod "1f871e4d-ee38-11e6-969d-080027859f43" (UID: "1f871e4d-ee38-11e6-969d-080027859f43") with: invalid character '/' looking for beginning of value
```
## Steps To Reproduce
 * Deploy a pod YAML in Kubenertes with a bad volume name similar to the following where volume `xxxtest-vol-1` does not exist.
  ```
apiVersion: v1
kind: Pod
metadata:
  name: pod-0
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: pod-0
    volumeMounts:
    - mountPath: /test-pd
      name: vol-0
  volumes:
  - name: vol-0
    flexVolume:
      driver: rexray/flexrex
      fsType: ext4
      options:
        volumeID: xxxtest-vol-1
        forceAttach: "true"
        forceAttachDelay: "15"
```
 * Observe the reported error in Kubernetes with `kubectl describe pod`
 * Verify that the REX-Ray log in `/var/log/rexray.log` display the real reason for failure.
