### ISSUE TITLE
EFS detach still has "attachments" section when doing volume ls

### ISSUE THREAD

**Issue by dvonthenen** [codedellemc/rexray#737]
# Summary
After detaching EFS, I would expect doing a volume ls would yield no attachments section. AWS console shows the device is available in the screenshot confirming that it is detached. Is this the expected behavior?

## Version
```shell
root@ip-10-0-0-11 ec2-user]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0+2+dirty
OsArch: Linux-x86_64
Branch: master
Commit: 845158ee1f650e8cab67ba29a9d6d5c769944f2c
Formed: Tue, 21 Feb 2017 12:14:42 EST

libStorage
----------
SemVer: 0.4.0+8
OsArch: Linux-x86_64
Branch: master
Commit: f0aa0a1f9a553ed77767e7285ab0dc1f3dd7aca9
Formed: Tue, 21 Feb 2017 12:46:30 EST
```

## Expected Behavior
After detaching, I would expect the "attachments" section to be gone.

## Actual Behavior
The "attachments" section is still present.

## Steps To Reproduce
```shell
[root@ip-10-0-0-11 ec2-user]# sudo rexray volume create mytests --size 16 | grep mytests | awk '{print $2}'
mytests
[root@ip-10-0-0-11 ec2-user]# sudo rexray volume ls mytests --format=jsonp
[
  {
    "attachmentState": 3,
    "name": "mytests",
    "size": 6144,
    "id": "fs-0c04cda5",
    "type": ""
  }
][root@ip-10-0-0-11 ec2-user]# sudo rexray volume attach mytests
ID           Name     Status    Size
fs-0c04cda5  mytests  attached  6144
[root@ip-10-0-0-11 ec2-user]# sudo rexray volume ls mytests --format=jsonp
[
  {
    "attachments": [
      {
        "deviceName": "",
        "instanceID": {
          "id": "subnet-f99548b0",
          "driver": "efs"
        },
        "status": "Exported",
        "volumeID": "fs-0c04cda5"
      }
    ],
    "attachmentState": 2,
    "name": "mytests",
    "size": 6144,
    "id": "fs-0c04cda5",
    "type": ""
  }
][root@ip-10-0-0-11 ec2-user]# sudo rexray volume detach mytests
ID           Name     Status     Size
fs-0c04cda5  mytests  available  6144
[root@ip-10-0-0-11 ec2-user]# sudo rexray volume ls mytests --format=jsonp
[
  {
    "attachments": [
      {
        "deviceName": "",
        "instanceID": {
          "id": "subnet-f99548b0",
          "driver": "efs"
        },
        "status": "Exported",
        "volumeID": "fs-0c04cda5"
      }
    ],
    "attachmentState": 2,
    "name": "mytests",
    "size": 6144,
    "id": "fs-0c04cda5",
    "type": ""
  }
``` 

## Configuration Files
```yaml
rexray:
  logLevel: debug
  modules:
    rexray:
      type: docker
      libstorage:
        service: efs
      host: unix:///run/docker/plugins/rexray.sock
libstorage:
  service: efs
  integration:
    volume:
      operations:
        mount:
          preempt: true
efs:
  accessKey: [ACCESS_KEY]
  secretKey: [SECRET_KEY]
```

Proper formatting of pasted content is very important as structured data can
sometimes be accidentally recorded incorrectly, affecting the desired outcome.

## Logs
[rexray.txt](https://github.com/codedellemc/rexray/files/791105/rexray.txt)
![available](https://cloud.githubusercontent.com/assets/12752197/23179125/ac0c44b0-f821-11e6-82ed-bf3b513997f4.png)
