### ISSUE TITLE
Attached Block Storage For Each Replicated Swarm Service Instance

### ISSUE THREAD

**Issue by jamespedwards42** [codedellemc/rexray#765]
What is the intended behavior when using write capable attached block storage, e.g. EC2 EBS, with a Swarm Service that is replicated more than one time?

If it isn't currently possible, would it be possible to automatically name space each drive (-1, -2, etc.) to match each service instance (container)?

**Comment by kacole2** [comment]
Hi @jamespedwards42 as you may have already guessed, we can't break the laws of block storage. Only a single host (and a single container for that matter) can have RW access to a block volume. 

I know @cduchesne has seen this and will respond after the weekend is over. We have a pretty good idea of what you are trying to do and have Swarm almost act like a Kubernetes Pod architecture.

**Comment by jamespedwards42** [comment]
@kacole2 Thanks for the heads up ... just to add why I think this would be useful, with the current behavior you have to copy/paste your service config N times in a compose file and end up loosing the natural load balancing of a replicated Docker Swarm Service.

**Comment by clintonskitson** [comment]
@jamespedwards42 Interesting thread here. Can you expand at all with exact configurations at a Swarm level that you configure for this purpose?

**Comment by jamespedwards42** [comment]
Here is a stripped down Docker Swarm Compose file to focus on the relevant parts:

```yaml
version: '3.1'
# docker stack deploy --compose-file=ec2-compose.yml mystack

services:
 my_service:
  image: org/image
  volumes:
   - my_volume:/dir
  deploy:
    mode: replicated
    replicas: 1
  command: ['cmd']
  
volumes:
  my_volume:
    driver: rexray/ebs
    driver_opts:
      size: 100
      volumeType: gp2
      fsType: ext4
      availabilityZone: us-east-1e
```

The idea is that if `replicas` is increased, rexray would be able to dynamically namespace and create a drive for each container instance. Otherwise, you have to define my_service_1, my_service_2, etc. and my_volume_1, my_volume_2, etc.

**Comment by clintonskitson** [comment]
Yup very interesting. That actually looks to be a layer of logic the Swarm or Compose should be taking on. From our perspective, Docker makes requests of us for specific volume names. We don't have any visibility currently into how the volume is being used, ie. part of Swarm or replicas. It would be Swarm that auto-generates new volume names and performs specific operations to keep or destroy the volumes as containers are re-generated.

Does that make sense?

**Comment by jamespedwards42** [comment]
@clintonskitson I see, thanks for clarifying.  I will look into whats the best way to propose this feature request to Docker.

**Comment by jaschaio** [comment]
The solution proposed in 804#issuecomment-377797386 appears to be working for me. I get the same number of rexray volumes than the replicas of the service I have defined.

```
volumes:
  data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-vol'
    driver: cloudstor:aws
```
