### ISSUE TITLE
Rexray config has one API entry - what if that manager API fails - that manager stops responding for some reason (reboot, halt, service failure)

### ISSUE THREAD

**Issue by andan02** [codedellemc/rexray#772]
# Summary
In the rexray config there is a spot for only one API IP address.  If this node fails to be responsive, how do we contact the other manager(s) in the cluster to keep operating without interruption?

## Version
```[root@devpywdcsf00101 ~]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.8.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 30e9082dd9917f0d218ca981f886d701110ce5f5
Formed: Fri, 24 Feb 2017 21:00:28 CST

libStorage
----------
SemVer: 0.5.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 35c7b6d96d5f17aa0c0379924615ae22c1ad3d45
Formed: Fri, 24 Feb 2017 20:59:00 CST
```

## Expected Behavior
I would expect a way to contact the API on any manager if one manager fails, from any rexray driver in the cluster

## Actual Behavior
If a scaleio manager stops responding, rex ray fails to operate against scaleio, and docker fails to have a storage backend

## Steps To Reproduce
Reboot the manager that is configured inside rexray as the API endpoint 

## Configuration Files
```yaml
rexray:
  service: scaleio
libstorage:
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://10.183.16.118/api
          thinOrThick: ThinProvisioned
          insecure: true
          userName: admin
          password: Cluster1!
          systemName: help1
          protectionDomainName: protection_domain_help
          storagePoolName: help_pool
```
