### ISSUE TITLE
Unable to create a volume on Azure

### ISSUE THREAD

**Issue by cecchisandrone** [codedellemc/rexray#779]
# Summary
I would like to test Rexray on my Azure storage account. I tried to create a volume in the following ways:
`docker volume create --driver=rexray --name=test --opt=size=1`
`sudo rexray volume create test --size=1`

and I receive the following error:

`Error response from daemon: create test: VolumeDriver.Create: {"Error":"Post http://libstorage-server/volumes/azureud: EOF"}`

## Version
```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.8.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 30e9082dd9917f0d218ca981f886d701110ce5f5
Formed: Sat, 25 Feb 2017 03:00:28 UTC

libStorage
----------
SemVer: 0.5.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 35c7b6d96d5f17aa0c0379924615ae22c1ad3d45
Formed: Sat, 25 Feb 2017 02:59:00 UT
```

## Expected Behavior
Volume should be created and visible if I run 'docker volume ls' or `sudo rexray volume ls`

## Actual Behavior
Error: `Error response from daemon: create test: VolumeDriver.Create: {"Error":"Post http://libstorage-server/volumes/azureud: EOF"}`

## Steps To Reproduce

- Run: `sudo rexray volume create test --size=1`

## Configuration Files
```yaml
rexray:
  logLevel: debug
libstorage:
  service: azureud
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
azureud:
  subscriptionID: xxx
  tenantID: xxx
  resourceGroup: xxx
  storageAccount: xxx
  storageAccessKey: xxx
  clientID: xxx
  clientSecret: xxx
```

## Logs

https://gist.github.com/cecchisandrone/902ea8eb84d283157b7d9476b52a7dc9
