### ISSUE TITLE
S3fs plugin - service update cause a "Error": "oci runtime error: container_linux.go:247

### ISSUE THREAD

**Issue by gprivitera** [codedellemc/rexray#780]
# Bug Reports
I'm currently using a global service while using a swarm mode of 5 machines. 
Each task of my service (nginx) is using the latest s3fs plugin and mounts the same volume in read-only mod (so only one s3 bucket).
Usually everything works smooth but sometimes between service updates I get this error:

```
"Error": "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/var/lib/docker/plugins/ebb571a6da1effeafa024e841ed6d42ccba0ac0dd740f759a28fc01feff41cd6/rootfs/var/lib/libstorage/volumes/VOLUME-NAME/data\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/1bc352d5c2d7a122d038e3fef646ae011837258d8c9fc343ab737292cd34af60\\\\\\\" at \\\\\\\"/TARGET/FOLDER\\\\\\\" caused \\\\\\\"stat /var/lib/docker/plugins/ebb571a6da1effeafa024e841ed6d42ccba0ac0dd740f759a28fc01feff41cd6/rootfs/var/lib/libstorage/volumes/VOLUME-NAME/data: no such file or directory\\\\\\\"\\\"\"\n", 
```

## Version
Using latest version of s3fs plugin.

## Expected Behavior
Normal update of the tasks of my service.

## Actual Behavior
Some tasks (or sometimes all of them) fail to restart, and the status of my service ends up being something like 2/5 instead of 5/5. 

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

I'm using `docker stack deploy` with a 3.1 compose file, omitting the non-interesting parts:
```
...
  nginx:
    image: nginx
    ...
    volumes:
      - VOLUME-NAME:/TARGET/FOLDER:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
...
volumes:
  VOLUME-NAME:
    external: true
...
```
The VOLUME-NAME volume was created before hand correctly.

To solve this situation I usually disable and re-enable the plugin in the machines where the service tasks didn't start (even a machine restart works), then I remove my service completely and redeploy it.

## Configuration Files
Default configuration for s3fs, just added my AWS id and secret key as env variable on plugin installation.
