### ISSUE TITLE
make directories individually configurable

### ISSUE THREAD

**Issue by gpaul** [codedellemc/rexray#799]
# Summary
All REX-Ray directories are relative to $REXRAY_HOME. 

This places hard and unnecessary requirements on users' file system layouts. 

For example, DC/OS would like to place the `config.yaml` file somewhere like /opt/mesosphere/etc/rexray/config.yaml to fit with the rest of our configuration management strategy. 

This would enable seamless upgrades from earlier versions of REX-Ray, something which is currently impossible due to changes in the configuration file schema. 

The schema changes from v0.3.3 to v0.8.2 require our users to manually rewrite the configuration file on every node, which is obviously blocks us from upgrading.

If we could decide on a strategy here I would be happy to submit a PR.

**Comment by akutz** [comment]
Hi @gpaul,

> This places hard and unnecessary requirements on users' file system layouts.

How so? I'd argue it makes things incredibly portable. This is very much like many software applications with which I've worked over the years. If you would like the configuration file to be there simply set `REXRAY_HOME` to `/opt/mesosphere/`.

**Comment by akutz** [comment]
Hi @gpaul,

Or use `REXRAY_HOME` in concert with symlinks:

`$ export REXRAY_HOME=/opt/rexray/v0.8.2`
`$ ln -s /opt/rexray/v0.8.2/etc/rexray/config.yaml /opt/mesosphere/etc/rexray/config.yaml`

When you want to use a diff version of REX-Ray or diff config file change your symlink.

Also, the scheme is backwards compatible for the most part via a lot of effort on our end to ensure it so. Please let us know which piece you've found is not backwards compatible.

**Comment by gpaul** [comment]
@akutz Thanks for the quick response.

> How so? I'd argue it makes things incredibly portable.

Does the following not look odd to you?

> /tmp/rexray/etc/rexray
/tmp/rexray/var/log/rexray
/tmp/rexray/var/run/rexray
/tmp/rexray/var/lib/rexray

To me, `/tmp/anything/var/log|lib|run` looks very strange.

The software I'm used to allows you to specify a config file using, say `-f /etc/rexray/custom.rexray.conf` which, of course, defaults to `/etc/rexray/rexray.conf` when not specified. 

That config file then includes various other parameters like `log_dir:`, `run_dir:` and `data_dir:`.

**Comment by gpaul** [comment]
Regarding the schema changes: I think we just missed the libstorage bus and are still running RR v0.3.3.

Here are the different configuration files (the first predates my appointment at Mesosphere so I likely lack some context):

current:
```
rexray:
  loglevel: info
  modules:
    default-admin:
      host: tcp://127.0.0.1:61003
  storageDrivers:
  - ec2
  volume:
    unmount:
      ignoreusedcount: true
```

new:
```
rexray:
  loglevel: info
  service: ebs
libstorage:
  integration:
    volume:
      operations:
        unmount:
          ignoreusedcount: true
```
