### ISSUE TITLE
Docker Plugin `rexray/ebs` duplicates volumes when used in Docker Stack Volumes Declaration

### ISSUE THREAD

**Issue by marcellodesales** [codedellemc/rexray#824]
# Bug Reports
When used in Docker Stacks, the plugin `rexray/ebs` creates multiple volumes when a new execution.

## Version

Installed as Docker Plugin

```shell
docker plugin ls
ID                  NAME                DESCRIPTION              ENABLED
377f763d1293        rexray/ebs:latest   REX-Ray for Amazon EBS   true
```

## Expected Behavior
Since the initial volumes were created with `docker stack create -c registry.yml`, and given that the volumes in question were declared in the `registry.yml` file (Compose V3), I would expect that if there's such a volume with the given name, the RexRay orchestration would reuse the existing ones instead of creation new ones.

## Actual Behavior
New Volumes are created with the same name as before.

<img width="1260" alt="screen shot 2017-04-28 at 10 40 57 pm" src="https://cloud.githubusercontent.com/assets/131457/25553302/b5a7d4e0-2c64-11e7-9fcf-bd267d61f57f.png">

* The `available` volumes were previously created in the first run of `docker stack create`, while the ones `in-use` are the ones with the second `docker stack create`.

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. Install

```
docker plugin install --grant-all-permissions rexray/ebs EBS_ACCESSKEY=A********A EBS_SECRETKEY=4G******LL EBS_REGION=****
latest: Pulling from rexray/ebs
bbf138eca3af: Verifying Checksum
bbf138eca3af: Download complete
Digest: sha256:4af99fcfa0cb1a2b0a28f562ce70a1979321ff607370fd9cb37a5caf130652ee
Status: Downloaded newer image for rexray/ebs:latest
Installed plugin rexray/ebs
```
2. Create the stack file `registry.yml` (See below)

3. `docker stack deploy -c registry.yml registry`

4. `docker stack rm  registry`    <<<<----- Good! Did NOT delete the volumes

5. `docker stack deploy -c registry.yml registry`   <<<------ Creates New instead 

## Configuration Files

```yml
version: '3'

services:

  registry:
    image: registry:2
    ports:
      - "80:80"
    volumes:
      - configs:/conf/stack
      - configs:/datastorage
    deploy:
      replicas: 1
      labels: [APP=REGISTRY]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "registry"
    labels:
      net.company.docker.hub.type: "Database"
      net.company.docker.hub.info: "Docker Registry MySQL Server"
    deploy:
      replicas: 1
      labels: [APP=MYSQL]
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role != manager]

volumes:
  configs:
    driver: rexray/ebs

  mysql-data:
    driver: rexray/ebs
```

Questions
------

* Is this the designed intention? What if I need to re-stack my entire cluster? Refreshes?
* Is there anything to do in the plugin to avoid this problem?
