### ISSUE TITLE
libstorage.host required in configuration even when defined under modules

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#827]
When testing modules, I noticed that libstorage.host is required at root of config even if also defined under defined modules.

```
# cat /etc/rexray/rexray-agent.yml
rexray:
  modules:
    default-docker:
      type: docker
      desc: default docker module
      host: unix:///run/docker/plugins/rexray1.sock
      libstorage:
        host: tcp://10.50.0.10:7979
        service: scaleio
    rexray2-module:
      type: docker
      desc: second module
      host: unix:///run/docker/plugins/rexray2.sock
      libstorage:
        host: tcp://10.50.0.20:7979
        service: scaleio2
```

```
ERRO[0000] default module(s) failed to initialize        error=libStorage host config missing time=1493682067471
```
