### ISSUE TITLE
Default TLS fails over Unix socket

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#832]
# Summary
When installing 0.9.0-rc1, and doing a simple auto-service config, the auto-tls config doesn't work. It doesn't match the certs hostname with what is there when using a Unix socket.

# Bug Reports

## Version
Please paste the output of `rexray version`. For example:

```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0-rc1
OsArch: Linux-x86_64
Branch: v0.9.0-rc1
Commit: 08b66840c38e06d6c3aaa86ce43e22e6e06bd3bc
Formed: Tue, 02 May 2017 20:40:29 UTC

libStorage
----------
SemVer: 0.6.0-rc1
OsArch: Linux-x86_64
Branch: v0.9.0-rc1
Commit: 68e4a3f6a21b542c730a5f56349c413a78846647
Formed: Tue, 02 May 2017 20:38:36 UTC
```

## Expected Behavior
I expected to be prompted to accept the fingerprint. But it also begs the question, do we use TLS over the Unix socket? I'm not sure.

## Actual Behavior
TLS is enabled, but the cert validation fails.

`Get http://libstorage-server/services: x509: certificate is valid for localhost, not /var/run/libstorage/919670668.sock`

## Steps To Reproduce
I was using the Cinder driver, but I think this will be true for any drivers...

Install the -RC

`curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- staged`

Place a valid config file (that's below) for your driver. The do

`rexray volume ls`

## Configuration Files

```yaml
libstorage:
  logging:
    level: debug
  service: cinder
cinder:
  authURL: http://10.138.0.2/identity/v3
  userName: demo
  password: xxxx
  tenantName: demo
  domainName: default
  availabilityZoneName: nova
  regionName: RegionOne
```

## Logs
https://gist.github.com/codenrhoden/42a058614bfaae13526ba17285a039c5
