### ISSUE TITLE
Unable to start REX-Ray with autogen certs in place

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#833]
# Summary
This builds off of #832, and could be a result of an invalid config on my part.

After performing the steps in #832, I set `libstorage.tls: false` and tested rexray standalone. All looked good. I then changed my rexray config.yml to the following:

```
libstorage:
  logging:
    level: debug
  service: cinder
  embedded: true
  host: tcp://127.0.0.1:7979
  server:
    services:
      cinder:
        driver: cinder
    endpoints:
      public:
        address: tcp://:7979
cinder:
  authURL: http://10.138.0.2/identity/v3
  userName: demo
  password: xxx
  tenantName: demo
  domainName: default
  availabilityZoneName: nova
  regionName: RegionOne
```

After doing that, I started REX-Ray with `systemctl start rexray` (This is on CentOS 7), and it panics on startup without being queried externally with the following error:

```
May 02 22:04:52 rex rexray[17922]: time="2017-05-02T22:04:52Z" level=panic msg="Get http://127.0.0.1:7979/services: x509: certificate signed by unknown authority"
May 02 22:04:52 rex rexray[17922]: panic: Get http://127.0.0.1:7979/services: x509: certificate signed by unknown authority [recovered]
May 02 22:04:52 rex rexray[17922]: panic: Get http://127.0.0.1:7979/services: x509: certificate signed by unknown authority [recovered]
May 02 22:04:52 rex rexray[17922]: panic: Get http://127.0.0.1:7979/services: x509: certificate signed by unknown authority [recovered]
May 02 22:04:52 rex rexray[17922]: panic: (*logrus.Entry) (0x14df7a0,0xc420503740)
```

Full logs linked to below. I'm not sure if this is happening because I had changed the `tls` config in between runs or not. FWIW, I did completely stop the `rexray` service, and removed files under `/var/run/rexray` and `/var/run/libstorage` and retried this multiple times. All the same result.

# Bug Reports

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0-rc1
OsArch: Linux-x86_64
Branch: v0.9.0-rc1
Commit: 08b66840c38e06d6c3aaa86ce43e22e6e06bd3bc
Formed: Tue, 02 May 2017 20:40:29 UTC

libStorage
----------
SemVer: 0.6.0-rc1
OsArch: Linux-x86_64
Branch: v0.9.0-rc1
Commit: 68e4a3f6a21b542c730a5f56349c413a78846647
Formed: Tue, 02 May 2017 20:38:36 UTC
```

## Expected Behavior
The auto-TLS should work in client/server on the same host. I expected to be prompted for accepting the fingerprint, and w/o having to edit any TLS related configs in the config file

## Actual Behavior
REX-Ray doesn't start.

## Configuration Files
```
libstorage:
  logging:
    level: debug
  service: cinder
  embedded: true
  host: tcp://127.0.0.1:7979
  server:
    services:
      cinder:
        driver: cinder
    endpoints:
      public:
        address: tcp://:7979
cinder:
  authURL: http://10.138.0.2/identity/v3
  userName: demo
  password: xxxx
  tenantName: demo
  domainName: default
  availabilityZoneName: nova
  regionName: RegionOne
```
I do not believe this behavior is driver specific.

There are TLS files in `/etc/libstorage/tls`

```
[root@rex ~]# ls -al /etc/libstorage/tls/
total 8
drwxr-xr-x. 2 root root   50 May  2 20:59 .
drwxr-xr-x. 3 root root   17 May  2 04:21 ..
-rw-r--r--. 1 root root 1164 May  2 20:59 libstorage.crt
-rw-------. 1 root root 1679 May  2 20:59 libstorage.key
```

### Service Log
https://gist.github.com/codenrhoden/4c7688644e52e191ec525a4f8cd9d8cd

### Client Log
None -- never ran the client
