### ISSUE TITLE
Rex-ray driver failed to initialize for Cinder

### ISSUE THREAD

**Issue by olivibernard** [codedellemc/rexray#856]
# Summary
I get an error when I start rexray.

# Bug Reports

## Version
```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 23:38:11 CEST

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 23:36:11 CEST
```

## Expected Behavior
Rexray is started and can work with openstack/cinder.

## Actual Behavior
Exit in failure, with this message
error starting libStorage server

## Steps To Reproduce
`# /usr/bin/rexray start -f -l debug`

## Configuration Files
`/etc/rexray/config.yml`

```yaml
libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: cinder
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
  server:
    services:
      cinder:
        driver: cinder
cinder:
  authURL:              https://openstack_url:5000/v2.0
  userDomainName:       default
  userName:             myname
  tenantID:             2658469f7540487fa63ffd354eca2ebf
  password:             xxxxxx
  domainName:           mydomain
  availabilityZoneName: nova
  regionName:           region1
```

### Client Log
https://gist.github.com/olivibernard/2dfdabf87f054008e1514993b4481c7d

Thanks for your help !
