### ISSUE TITLE
Unable to mount azureud volume using `rexray volume mount`

### ISSUE THREAD

**Issue by briantd** [codedellemc/rexray#858]
# Summary
I am unable to mount an Azure rexray volume on an azure instance.

# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version
Please paste the output of `rexray version`. For example:

```shell
swarm-manager000000:/home/docker# rexray version
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1494961811674 val=[rexray version]
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 21:38:11 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 21:36:11 UTC
DEBU[0000] completed cli execution                       time=1494961811675
INFO[0000] exiting process                               time=1494961811675
DEBU[0000] completed onExit at end of program            time=1494961811675
```

## Expected Behavior
Volume mounted on instance

## Actual Behavior
Fatal error returned:
`FATA[0001] error mounting volume                         error.inner.inner.inner.vmName=swarm-manager000000 error.status=500 volume=myvolume2.vhd`

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. The first step should always be enabling `debug` logging.
  * Open the file `/etc/rexray/config.yml`
  * Set the log level for both REX-Ray and libStorage to `debug` and enable
HTTP request and response tracing for libStorage:
```yaml
rexray:
  logLevel:        debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
```

2. Create rexray azure volume and confirm it exists
`rexray volume create myvolume2`
```
rexray volume ls
ID             Name       Status     Size
...
myvolume2.vhd  myvolume2  available  128
```

From Azure UI:
<img width="857" alt="screenshot of google chrome 5-16-17 12-23-04 pm" src="https://cloud.githubusercontent.com/assets/94055/26124177/6b6d8718-3a32-11e7-8cc8-82903c844585.png">

3. Attempt to mount azure volume
`rexray volume mount myvolume2`

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```yaml
swarm-manager000000:/home/docker# cat /etc/rexray/config.yml
rexray:
  logLevel: debug
  modules:
    default-docker:
      disabled: false
libstorage:
  logging:
    level: debug
    httpRequests:  true
    httpResponses: true
  server:
    tasks:
      exeTimeout: 120s
  service: azureud
  integration:
    volume:
      operations:
        mount:
          preempt: true
        remove:
          disable: true
azureud:
  subscriptionID: d...0
  resourceGroup: g...g
  tenantID: 5...4
  storageAccount: g...2
  storageAccessKey: X...g==
  clientID: 0...b
  clientSecret: k...U
  useHTTPS: true
  container: rexrayvolumes
```

Proper formatting of pasted content is very important as structured data can
sometimes be accidentally recorded incorrectly, affecting the desired outcome.

## Logs
It is very important when filing an issue to include associated logs. There are
two different logs about which to be concerned: the service log (if REX-Ray is
running as a service) and the client log.

### Service Log
The REX-Ray service log file is stored at `/var/log/rexray/rexray.log`. Instead
of pasting the entire log file into this issue, please create a new
[gist](https://gist.github.com/) and paste the log file's contents there.
Please name the file `rexray-service.log` in the gist. The proper extension will
indicate how to format the contents.

See [gist](https://gist.github.com/briantd/92486fce130c59ab0fc4b76ec1125610) -- logging was produced using `sudo rexray service -l debug start -f` so that debug log is in foreground.

In contrast, this [gist](https://gist.github.com/briantd/85b1347c2c3d491842748c7bea8d8a55) didn't use foreground mode, and was created before I realized lsscsi needed to be installed.

Conclusion = "missing ID" error is the result of no lsscsi?

### Client Log
The REX-Ray client will emit all of its logs to the console when operating with
debug logging enabled. Simply copy the contents of the console and paste them
into the same gist as above naming the file `rexray-client.log.sh`. The `sh`
extension will cause the contents to be formatted as if they were emitted
to the shell, which they were.

See [gist](https://gist.github.com/briantd/92486fce130c59ab0fc4b76ec1125610) -- logging was produced using `sudo rexray service -l debug start -f` so that debug log is in foreground.

In contrast, this [gist](https://gist.github.com/briantd/85b1347c2c3d491842748c7bea8d8a55) didn't use foreground mode, and was created before I realized lsscsi needed to be installed.
