### ISSUE TITLE
Cinder volume is not detached when a docker service using it is drained off a swarm node

### ISSUE THREAD

**Issue by akailash** [codedellemc/rexray#861]
# Summary
I have a docker service running on a 3 node docker swarm using openstack instances. This service uses a cinder volume for data persistance. However if I drain the node where the service is hosted, the service cannot be started on other node due to the volume still remaining attached to the drained node. Same behaviour is seen if a node is rebooted.

# Bug Reports

## Version
Please paste the output of `rexray version`. For example:

```shell
ubuntu@swarm1-0:~$ rexray version
INFO[0004] updated log level                             logLevel=debug
DEBU[0004] os.args                                       time=1495001860746 val=[rexray version]
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 21:38:11 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 21:36:11 UTC
DEBU[0004] completed cli execution                       time=1495001860747
INFO[0004] exiting process                               time=1495001860748
DEBU[0004] completed onExit at end of program            time=1495001860749
ubuntu@swarm1-0:~$ 
```

## Expected Behavior
I expect the rexray driver to detach/unmount the volume when the service is drained from the node (Same behaviour as it does when the service is removed)

## Actual Behavior
The volume remains attached to the node and the service is unable to access the volume again due to its status "In-use".

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. The first step should always be enabling `debug` logging.
2. Start a docker service using the rexray driver to mount a cinder volume.
Eg: 
`sudo docker service create --name nexus  --mount type=volume,src=nexus-data,dst=/nexus-data,volume-driver=rexray sonatype/nexus3`

3. Find the node where the service is hosted and drain that node
```shell
ubuntu@swarm1-0:~$ docker service ps nexus
ID                  NAME                IMAGE                    NODE                DESIRED STATE       CURRENT STATE          ERROR                              PORTS
pzs5cbvc1l2b        nexus.1             sonatype/nexus3:latest   swarm1-2            Running             Running 2 hours ago                                       
ubuntu@swarm1-0:~$ docker node update --availability drain swarm1-2
swarm1-2
```
4. Check what happens to the service using the rexray volume
```shell
ubuntu@swarm1-0:~$ docker service ps --no-trunc nexus
ID                          NAME                IMAGE                                                                                            NODE                DESIRED STATE       CURRENT STATE                     ERROR                                                                         PORTS
new2ysfx1baypst5y3ycqprhu   nexus.1             sonatype/nexus3:latest@sha256:41e7b1c4656346e3d60f62f2d3cddb26d0b20809ee4b8b8f4069470b9c3ff12e   swarm1-1            Ready               Rejected less than a second ago   "A volume named nexus-data already exists. Choose a different volume name."   
v4bhmpa4io73532ery5fr1aww    \_ nexus.1         sonatype/nexus3:latest@sha256:41e7b1c4656346e3d60f62f2d3cddb26d0b20809ee4b8b8f4069470b9c3ff12e   swarm1-0            Shutdown            Rejected 5 seconds ago            "A volume named nexus-data already exists. Choose a different volume name."   
ywcrpduezpf9ouq79m9s98lz0    \_ nexus.1         sonatype/nexus3:latest@sha256:41e7b1c4656346e3d60f62f2d3cddb26d0b20809ee4b8b8f4069470b9c3ff12e   swarm1-1            Shutdown            Rejected 10 seconds ago           "A volume named nexus-data already exists. Choose a different volume name."   
mp1j2rlhc3rxglpztdck4jrfd    \_ nexus.1         sonatype/nexus3:latest@sha256:41e7b1c4656346e3d60f62f2d3cddb26d0b20809ee4b8b8f4069470b9c3ff12e   swarm1-0            Shutdown            Rejected 15 seconds ago           "A volume named nexus-data already exists. Choose a different volume name."   
t07m2p8vpnnlvu5cifef5texi    \_ nexus.1         sonatype/nexus3:latest@sha256:41e7b1c4656346e3d60f62f2d3cddb26d0b20809ee4b8b8f4069470b9c3ff12e   swarm1-0            Shutdown            Rejected 20 seconds ago           "A volume named nexus-data already exists. Choose a different volume name."   
ubuntu@swarm1-0:~$ 
```

## Configuration Files
`/etc/rexray/config.yml`

```yaml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 2
        mount:
          preempt: true
cinder:
  authUrl:              http://****:5000/v3
  username:             ****
  password:             ****
  tenantId:             ****
  tenantName:           ****
  identityApiVersion:   3
  domainName:           ****
  regionName:           ****
  availabilityZoneName: nova
```
`/etc/libstorage/config.yml`
```yaml
libstorage:
  logging:
    level:         debug
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
cinder:
  authUrl:              http://****:5000/v3
  username:             ****
  password:             ****
  tenantId:             ****
  tenantName:           ****
  domainName:           ****
  regionName:           ****
  availabilityZoneName: nova

```

## Logs
Rexray logs do not show any error/debug messages. The docker service however is unable to mount the volume since it is already attached to a node. Here is the log showing the steps followed and corresponding logs
[Click here for logs](https://gist.github.com/akailash/a51fbdc806b2134ba07ac943bfdefca2)
