### ISSUE TITLE
Volume not created from snapshot when using EBS driver

### ISSUE THREAD

**Issue by MrHash** [codedellemc/rexray#871]
## Version
```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 21:38:19 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 21:37:49 UTC

```

## Expected Behavior
EBS volume should be created from snapshot id.

## Actual Behavior
EBS volume is created but not from snapshot.

## Steps To Reproduce
```
docker plugin install rexray/ebs EBS_ACCESSKEY=redacted EBS_SECRETKEY=redacted EBS_REGION=ap-northeast-1
docker volume create -d rexray/ebs --name testvol01 --opt=size=8 --opt=volumeType=gp2 --opt=snapshotID=snap-0e2999ef7a0d48437
```

## Configuration Files
```yaml
rexray:
  loglevel: debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
  service: ebs
  integration:
    volume:
      operations:
        create:
          default:
            fsType: ext4
        mount:
          preempt: false
  server:
    services:
      ebs:
        driver: ebs
ebs:
  accessKey: redacted
  secretKey: redacted
  region: ap-northeast-1
```
