### ISSUE TITLE
EBS Volume are not destroy when a docker stack is rm

### ISSUE THREAD

**Issue by GabKlein** [codedellemc/rexray#882]
Using the following configuration, when I run `docker stack rm my-stack` the volume is well de-attached but still persisted. What would be best way to remove the EBS volume as soon as the stack as been rm?

I'm using `rexray/ebs:latest`

```
version: '3.2'

volumes:
  data_registry:
    driver: rexray/ebs
    driver_opts:
      size: 100
      fsType: ext4

services:
  registry:
    image: registry:2
    volumes:
      - data_registry:/var/lib/registry
```
