### ISSUE TITLE
Unable to configure REX-Ray server using environment variables only

### ISSUE THREAD

**Issue by ngokeith** [codedellemc/rexray#886]
# Summary
Unable to configure a centralized REX-Ray server using environment variables only (without a config file).

Specifically, I was trying to configure `rexray.modules.default-docker.disabled` and `libstorage.server.services`.  Using `rexray env`, I can see that the config key is missing, or the config value is incorrect.

Is this possible through environment variables only?

## Version
```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0+1
OsArch: Linux-x86_64
Branch: master
Commit: 89c51983f00997b00ee84af4e315c0ad460804db
Formed: Wed, 07 Jun 2017 16:19:34 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: (detached from fa055d6
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 07 Jun 2017 16:19:05 UTC
```

## Steps To Reproduce

After setting the environment variables, the output from `rexray env` is missing/has incorrect config values for
 * **REXRAY_MODULES_DEFAULT-DOCKER_DISABLED**
 * **LIBSTORAGE_SERVER_SERVICES_VIRTUALBOX_DRIVER**
 * **LIBSTORAGE_SERVER_ENDPOINTS_PUBLIC_ADDRESS**

```shell
$ env | egrep 'REXRAY|LIBSTORAGE|VIRTUALBOX' | sort -r
VIRTUALBOX_VOLUMEPATH=/private/var/folders/xj/k7jbw6ws44s81znnk2nvvrk9p68y5g/T/tmp.Hqa8BXpb/.vagrant/volumes
REXRAY_MODULES_DEFAULT-DOCKER_DISABLED=true
REXRAY_LOGLEVEL=debug
LIBSTORAGE_SERVER_SERVICES_VIRTUALBOX_DRIVER=virtualbox
LIBSTORAGE_SERVER_ENDPOINTS_PUBLIC_ADDRESS=tcp://:7979
LIBSTORAGE_LOGGING_LEVEL=debug
LIBSTORAGE_LOGGING_HTTPRESPONSES=true
LIBSTORAGE_LOGGING_HTTPREQUESTS=true
LIBSTORAGE_HOST=tcp://127.0.0.1:7979
LIBSTORAGE_EMBEDDED=true
LIBSTORAGE_CLIENT_TYPE=controller

$ rexray env | egrep 'DOCKER_DISABLED|HOST|EMBEDDED|CLIENT_TYPE|SERVER_ENDPOINTS|SERVER_SERVICES|LOGGING|VIRTUALBOX' | sort -r
VIRTUALBOX_VOLUMEPATH=/private/var/folders/xj/k7jbw6ws44s81znnk2nvvrk9p68y5g/T/tmp.Hqa8BXpb/.vagrant/volumes
VIRTUALBOX_USERNAME=
VIRTUALBOX_TLS=false
VIRTUALBOX_SCSIHOSTPATH=/sys/class/scsi_host/
VIRTUALBOX_PASSWORD=
VIRTUALBOX_LOCALMACHINENAMEORID=
VIRTUALBOX_ENDPOINT=http://10.0.2.2:18083
VIRTUALBOX_DISKIDPATH=/dev/disk/by-id
VIRTUALBOX_CONTROLLERNAME=SATA
S3FS_HOSTNAME=node0
REXRAY_MODULES_DEFAULT-DOCKER_HOST=unix:///run/docker/plugins/rexray.sock
REXRAY_MODULES_DEFAULT-DOCKER_DISABLED=false
REXRAY_HOST=
LIBSTORAGE_TLS_KNOWNHOSTS=/etc/libstorage/tls/known_hosts
LIBSTORAGE_LOGGING_STDOUT=
LIBSTORAGE_LOGGING_STDERR=
LIBSTORAGE_LOGGING_LEVEL=debug
LIBSTORAGE_LOGGING_HTTPRESPONSES=true
LIBSTORAGE_LOGGING_HTTPREQUESTS=true
LIBSTORAGE_HOST=tcp://127.0.0.1:7979
LIBSTORAGE_EMBEDDED=true
LIBSTORAGE_CLIENT_TYPE=controller
ISILON_NFSHOST=
```

However, using a config file instead of environment variables worked as expected.

```yaml
# /etc/rexray/config.yml
rexray:
  modules:
    default-docker:
      disabled: true
  logLevel: debug
libstorage:
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
  host: tcp://127.0.0.1:7979
  embedded: true
  client:
    type: controller
  server:
    endpoints:
      public:
        address: tcp://:7979
    services:
      virtualbox:
        driver: virtualbox
virtualbox:
  volumePath: /private/var/folders/xj/k7jbw6ws44s81znnk2nvvrk9p68y5g/T/tmp.Hqa8BXpb/.vagrant/volumes
```

Here is the output from `rexray env`.  This time, **REXRAY_MODULES_DEFAULT-DOCKER_DISABLED**, **LIBSTORAGE_SERVER_SERVICES_VIRTUALBOX_DRIVER** and **LIBSTORAGE_SERVER_ENDPOINTS_PUBLIC_ADDRESS** are correct.

```shell
$ rexray env | egrep 'DOCKER_DISABLED|HOST|EMBEDDED|CLIENT_TYPE|SERVER_ENDPOINTS|SERVER_SERVICES|LOGGING|VIRTUALBOX' | sort -r
VIRTUALBOX_VOLUMEPATH=/private/var/folders/xj/k7jbw6ws44s81znnk2nvvrk9p68y5g/T/tmp.Hqa8BXpb/.vagrant/volumes
VIRTUALBOX_USERNAME=
VIRTUALBOX_TLS=false
VIRTUALBOX_SCSIHOSTPATH=/sys/class/scsi_host/
VIRTUALBOX_PASSWORD=
VIRTUALBOX_LOCALMACHINENAMEORID=
VIRTUALBOX_ENDPOINT=http://10.0.2.2:18083
VIRTUALBOX_DISKIDPATH=/dev/disk/by-id
VIRTUALBOX_CONTROLLERNAME=SATA
S3FS_HOSTNAME=node0
REXRAY_MODULES_DEFAULT-DOCKER_HOST=unix:///run/docker/plugins/rexray.sock
REXRAY_MODULES_DEFAULT-DOCKER_DISABLED=true
REXRAY_HOST=
LIBSTORAGE_TLS_KNOWNHOSTS=/etc/libstorage/tls/known_hosts
LIBSTORAGE_SERVER_SERVICES_VIRTUALBOX_DRIVER=virtualbox
LIBSTORAGE_SERVER_ENDPOINTS_PUBLIC_ADDRESS=tcp://:7979
LIBSTORAGE_LOGGING_STDOUT=
LIBSTORAGE_LOGGING_STDERR=
LIBSTORAGE_LOGGING_LEVEL=debug
LIBSTORAGE_LOGGING_HTTPRESPONSES=true
LIBSTORAGE_LOGGING_HTTPREQUESTS=true
LIBSTORAGE_HOST=tcp://127.0.0.1:7979
LIBSTORAGE_EMBEDDED=true
LIBSTORAGE_CLIENT_TYPE=controller
ISILON_NFSHOST=
```
