### ISSUE TITLE
Docker EBS mount fails when using non-distinct volume name within an AZ

### ISSUE THREAD

**Issue by toddschilling** [codedellemc/rexray#990]
# Summary
I'm currently running an Elasticsearch cluster in Docker containers on AWS.  Containers are deployed using HashiCorp Nomad and is controlled using a Nomad job specification file.  This setup has been working very well as long as the volume names are unique within an availability zone.  However, when Nomad attempts to execute two of my Elasticsearch containers in the same AZ using the same volume name, both containers attempt to attach to the same disk and one fails.

## Version
```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 9c7b7329884bf2feeffe101fc5dc3a239730427d
Formed: Wed, 28 Jun 2017 20:09:01 UTC

libStorage
----------
SemVer: 0.6.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 7368564cc71be9a0dbe03ddfbaeda281232eee72
Formed: Wed, 28 Jun 2017 20:08:31 UTC
```

## Expected Behavior
I'm not sure.  It seems like this behavior may be by design but I'd like confirmation.  The logic to determine whether or not a volume is attached and to create a new one if it's already occupied might be overly complex.

## Actual Behavior
Both containers within the availability zone attempt to attach to the same volume instead of creating and attaching to two different volumes.

## Steps To Reproduce
Deploy multiple containers within the same availability zone using the following Nomad configuration.

```json
volume_driver = "ebs"
volumes = [
  "myservice.db:/usr/share/elasticsearch/data"
]
```

## Configuration Files

```yaml
cat <<EOF > /etc/rexray/config.yml
rexray:
  modules:
    default-docker:
      disabled: true
    ebs-docker:
      type:     docker
      host:     unix:///run/docker/plugins/ebs.sock
      spec:     /etc/docker/plugins/ebs.spec
      libstorage:
        service: ebs
libstorage:
  integration:
    volume:
      operations:
        create:
          default:
            type:   gp2
            size:   4
        mount:
          preempt: true
  server:
    services:
      ebs:
        driver: ebs
EOF
```

## Logs
It is very important when filing an issue to include associated logs. There are
two different logs about which to be concerned: the service log (if REX-Ray is
running as a service) and the client log.

### Service Log
The REX-Ray service log file is stored at `/var/log/rexray/rexray.log`. Instead
of pasting the entire log file into this issue, please create a new
[gist](https://gist.github.com/) and paste the log file's contents there.
Please name the file `rexray-service.log` in the gist. The proper extension will
indicate how to format the contents.

### Client Log
The REX-Ray client will emit all of its logs to the console when operating with
debug logging enabled. Simply copy the contents of the console and paste them
into the same gist as above naming the file `rexray-client.log.sh`. The `sh`
extension will cause the contents to be formatted as if they were emitted
to the shell, which they were.
